[package]
name = "mpm"
version = "0.1.0"
authors = ["Simon <simonhulse87@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14"
num = "0.3"
